[package]
license = "MIT OR Apache-2.0"
description = "Backend contracts and grid rendering for Clickless"
repository = "https://github.com/smresponsibilities/clickless"
readme = "../../README.md"
name = "clickless-backend-api"
version = "0.1.2"
edition = "2024"

[dependencies]
clickless-core = { version = "0.1.2", path = "../clickless-core" }
