[package]
name = "clickless-windows"
version = "0.1.0"
edition = "2024"

[dependencies]
clickless-core = { path = "../clickless-core" }
clickless-backend-api = { path = "../clickless-backend-api" }
windows-sys = { version = "0.61", features = [
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
] }

[target.'cfg(windows)'.dependencies]
tray-icon = { version = "0.25", default-features = false }

[dev-dependencies]
clickless-backend-api = { path = "../clickless-backend-api" }
