[package]
name = "clickless-macos"
version = "0.1.0"
edition = "2024"

[dependencies]
clickless-core = { path = "../clickless-core" }
clickless-backend-api = { path = "../clickless-backend-api" }

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = "0.24"
core-foundation = "0.10"

[dev-dependencies]
clickless-backend-api = { path = "../clickless-backend-api" }
